### ISSUE TITLE
Implement `GET /rsvp/:lastName/:firstName` endpoint to retrieve most recent RSVP for a user

### ISSUE THREAD

**Issue by huy-vuong** [house-cats/huyan#79]
**Path Parameters:**

- **`lastName`** last name for the RSVP to look up
- **`firstName`** first name for the RSVP to look up

**Response Status:**

- `200 OK` if RSVP found for `(first-name, last-name)` combination
- `400 Bad Request` if either `first-name` or `last-name` are blank (null, empty, or all whitespace chars)
- `404 Not Found` if no RSVP found for the given `(first-name, last-name)`
- `500 Internal Server Error` if any other errors get thrown

**Response Body:**

```javascript
const MealPreference = Object.freeze({
  Tahini: "TAHINI",
  TheTacoStand: "THE_TACO_STAND",
  MilongaEmpanadas: "MILONGA_EMPANADAS",
  TheSandwichSpot: "THE_SANDWICH_SPOT",
  KnockoutPizzeria: "KNOCKOUT_PIZZERIA",
  RegentsPizzeria: "REGENTS_PIZZERIA",
  PopPieCo: "POP_PIE_CO",
});

const rsvpSchema = object({
  submissionTime: date().required(), // Supplied by server, not client.
  attending: boolean().required(),
  firstName: string().required(),
  lastName: string().required(),
  mealPreference: string().required().oneOf(Object.values(MealPreference)),
  dietaryRestrictions: string().required(),
});
```

**Comment by YanZ777** [comment]
What's the endpoint name?

**Comment by huy-vuong** [comment]
> What's the endpoint name?

Oops. Didn't actually see this.

https://huy-dev-huyan.deta.dev/rsvp/:lastName/:firstName

^ Substitute `:lastName` and `:firstName` accordingly.
